sonar.projectKey=laraareck_integration-tests-jest-larareck
sonar.organization=laraareck
sonar.projectName=integration-tests-jest-larareck
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8